# Generated by Django 3.2.3 on 2021-07-05 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='EstadoCliente',
            new_name='idEstadoCliente',
        ),
        migrations.RenameField(
            model_name='repartidor',
            old_name='EstadoReparidor',
            new_name='idEstadoRepartidor',
        ),
    ]
