# Generated by Django 3.2.3 on 2021-07-05 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210704_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_Socios',
            fields=[
                ('idEstadoSocio', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Estado Socio')),
                ('GlosaEstadoSocio', models.CharField(max_length=50, verbose_name='Glosa Estado Socio')),
            ],
        ),
        migrations.CreateModel(
            name='Socios',
            fields=[
                ('idSocio', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Socio')),
                ('NombreSocio', models.CharField(max_length=200, verbose_name='Nombre Socio')),
                ('Telefono', models.CharField(max_length=12, verbose_name='Telefóno Socio')),
                ('Direccion', models.CharField(max_length=100, verbose_name='Dirección Socio')),
                ('Mail', models.CharField(max_length=50, verbose_name='E-mail Socio')),
                ('Web', models.CharField(max_length=100, verbose_name='Web Socio')),
                ('idEstadoSocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estado_socios')),
            ],
        ),
    ]
